var config = {
    version: 'sdk-samples/1.0.0', // this helps to identify telemetry generated by the samples
    apiKey: 'a42fcebd-5b43-4b89-a065-74450fb91255', // SDK DF
    apiKeyCC: '9c967f6b-a846-4df2-b43d-5167e47d81e1', // SDK+CC DF
    clientId: '2a4d1b96-d61e-423d-af87-df14cf07bcf2', // client id used to identify the app
    authLink: 'https://login.windows-ppe.net/common/oauth2/authorize', 
    redirectUri: 'http://localhost:12345/index.html', // redirect url
    authResource: 'https://webdir0d.tip.lync.com',
    responseType: 'token'
};