var config = {
    version: 'sdk-samples/1.0.0', // this helps to identify telemetry generated by the samples
    apiKey: 'a42fcebd-5b43-4b89-a065-74450fb91255', // SDK DF
    apiKeyCC: '9c967f6b-a846-4df2-b43d-5167e47d81e1', // SDK+CC DF
    clientId: '', //REPLACE EMPTY QUOTES WITH CLIENTID GENERATED FROM AZURE APP
    authLink: 'https://login.microsoftonline.com/common/oauth2/authorize?response_type=token',
    authResource: 'https://webdir0d.tip.lync.com',
    redirect_uri: 'http://localhost:55073/App/home/home.html'
};