var config = {
    version: 'build-demo-labB/1.0.0', // this helps to identify telemetry generated by the samples
    apiKey: 'a42fcebd-5b43-4b89-a065-74450fb91255', // SDK DF
    apiKeyCC: '9c967f6b-a846-4df2-b43d-5167e47d81e1', // SDK+CC DF
    clientId: '98267106-694b-4df2-8e06-fbbafd8a90e7',
    authLink: 'https://login.windows.net/common/oauth2/authorize?response_type=token',
    authResource: 'https://webdir.online.lync.com',
    origins: 'https://webdir.online.lync.com/autodiscover/autodiscoverservice.svc/root',
    redirect_uri: 'https://secondonlineapp.azurewebsites.net/App/home/home.html'  
};